site_name: OpenGL - Getting Started
site_author: deccer
site_url: https://deccer.github.io/opengl-getting-started
repo_name: deccer/opengl-getting-started
repo_url: https://github.com/deccer/opengl-getting-started
site_description: OpenGL Getting Started
copyright: Copyright 2023 deccer
theme:
  name: material
  font:
    text: Roboto Flex
    code: Roboto Mono
  palette:
    scheme: slate
    primary: pink
    accent: yellow
  language: en
  features:
    - navigation.tabs
    - navigation.instant.progress
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deccer/opengl-getting-started
      name: OpenGL Getting Started on Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/6mgNGk7
      name: opengl-getting-started on discord
  analytics:
    provider: google
    property: G-2FDD1M3R22

extra_css:
  - stylesheets/extra.css      

markdown_extensions:
  - admonition
  - footnotes
  - markdown.extensions.toc:
      permalink: true
  - attr_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
nav:
  - Home: index.md
  - Setup:
      - Setup: 00-setup/00-setup.md
      - Basic Application: 00-setup/01-basic-application.md
  - Basic Triangle:
      - Basic Triangle: 10-basic-triangle/10-basic-triangle.md
  - About: about.md
