site_name: OpenGL - Getting Started
site_author: deccer
site_url: https://deccer.github.io/opengl-getting-started
repo_name: deccer/opengl-getting-started
repo_url: https://github.com/deccer/opengl-getting-started
site_description: OpenGL Getting Started
copyright: Copyright 2023 deccer
theme:
  name: material
  logo: https://cdn-icons-png.flaticon.com/512/1949/1949895.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    scheme: slate
    primary: pink
    accent: yellow
  language: en
  features:
    - navigation.sections
    - navigation.indexes
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.footer
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deccer/opengl-getting-started
      name: OpenGL Getting Started on Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/6mgNGk7
      name: opengl-getting-started on discord
  analytics:
    provider: google
    property: G-2FDD1M3R22

extra_css:
  - stylesheets/extra.css      

markdown_extensions:
  - admonition
  - footnotes
  - markdown.extensions.toc:
      permalink: true
  - attr_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path:
        - ""
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - def_list
nav:
  - Home: index.md
  - Setup:
      - Setup: 00-setup/00-setup.md
  - Basics:
      - Basic Window: 01-basics/01-basic-window.md
      - Basic Window With Triangle: 01-basics/02-basic-window-and-triangle.md
  - Debugging:
      - Debugging: 02-debugging/01-debugging.md
      - Debug Callback:    
          - Debug Callback: 02-debugging/02-debug-callback.md
          - Debug Callback Exercises:      
            - Exercise 1: 02-debugging/02-debug-callback-exercise-01.md
            - Exercise 2: 02-debugging/02-debug-callback-exercise-02.md
          - RenderDoc: 02-debugging/03-renderdoc.md
          - RenderDoc Exercises: 
            - Exercise 1: 02-debugging/04-renderdoc-exercise-01.md
          - Nsight Graphics: 02-debugging/05-nsight-graphics.md
  #- Basic Application: 00-setup/01-basic-application.md
  #- Basic Triangle:
  #    - Basic Triangle: 10-basic-triangle/10-basic-triangle.md
  - About: about.md
